export const PRODUCTS = [
  {
    id: "1",
    category: "prebook",
    name: "Country Chicken Curry Cut (Skinless)",
    weight: "550-600 Gms · 1 Unit pcs · Serves 3 - 4",
    price: 349,
    oldPrice: 399,
    elite: true,
    image: require("../../assets/products/curry-cut-chicken.jpg"),
  },
  {
    id: "2",
    category: "mutton",
    name: "Goat Heart",
    weight: "150–180 Gms · 2 pcs · Serves 1",
    price: 149,
    image: require("../../assets/products/goat-heart.jpg"),
  },
  {
    id: "3",
    category: "mutton",
    name: "Mutton Kapura",
    weight: "150–180 Gms · 2 pcs · Serves 1",
    price: 119,
    oldPrice: 129,
    elite: true,
    image: require("../../assets/products/mutton-kapura.jpg"),
  },
  {
    id: "4",
    category: "elite",
    name: "Black Pomfret",
    weight: "150–180 Gms · 2 pcs · Serves 1",
    price: 419,
    image: require("../../assets/products/black-pomfret.jpg"),
  },
  {
    id: "5",
    category: "chicken",
    name: "Country Chicken Curry Cut (Skinless)",
    weight: "550-600 Gms · 1 Unit pcs · Serves 3 - 4",
    price: 349,
    oldPrice: 399,
    elite: true,
    image: require("../../assets/products/curry-cut-chicken.jpg"),
  },
];
